### ISSUE TITLE
"assert root_frame is None" fails in QGIS

### ISSUE THREAD

**Issue by s-m-e** [joerick/pyinstrument#91] opened 2020-05-30 17:10 UTC
I am trying to profile the startup of [QGIS](https://www.qgis.org)' embedded Python components. The following trick works with `cProfile`: I am injecting the profiler startup into [QGIS' Python initialization code through the `PYQGIS_STARTUP` environment variable](https://github.com/qgis/QGIS/blob/823426152798a94781081717f7f30091705a9f18/src/python/qgspythonutilsimpl.cpp#L61), which works sort of similar to `PYTHONSTARTUP`. Imagine a script named `start_profiler.py`:

```python
import os, cProfile
os._pr = cProfile.Profile()
os._pr.enable()
```

I can launch QGIS like this: `PYQGIS_STARTUP=$PWD/start_profiler.py qgis`. Once QGIS is loaded, I can open its internal Python console, stop the profiler, i.e. run `os._pr.disable()`, and extract its data. It works nicely.

I tried the same trick with `pyinstrument`, i.e. my `start_profiler.py` file now looks like this:

```python
import os
from pyinstrument import Profiler
os._pr = Profiler()
os._pr.start()
```

It works up to the point where I am stopping it with `os._pr.stop()`. However, getting some output from it fails, e.g. when I call `print(os._pr.output_text(unicode=True, color=True))`:

```python
Traceback (most recent call last):
  File "/conda/3/envs/qgis_py37/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "</conda/3/envs/qgis_py37/lib/python3.7/site-packages/pyinstrument/vendor/decorator.py:decorator-gen-7>", line 2, in output_text
  File "/conda/3/envs/qgis_py37/lib/python3.7/site-packages/pyinstrument/util.py", line 37, in caller
    return func(*args, **kwargs)
  File "/conda/3/envs/qgis_py37/lib/python3.7/site-packages/pyinstrument/profiler.py", line 97, in output_text
    return renderers.ConsoleRenderer(unicode=unicode, color=color, show_all=show_all, timeline=timeline).render(self.last_session)
  File "/conda/3/envs/qgis_py37/lib/python3.7/site-packages/pyinstrument/renderers/console.py", line 20, in render
    self.root_frame = self.preprocess(session.root_frame())
  File "/conda/3/envs/qgis_py37/lib/python3.7/site-packages/pyinstrument/session.py", line 77, in root_frame
    assert root_frame is None, ASSERTION_MESSAGE
AssertionError: Please raise an issue at http://github.com/pyinstrument/issues and let me know how you caused this error!
```

**Comment by joerick** [comment] 2021-04-03 22:38
I'm assuming this a dupe of #84

**Closed by joerick** 2021-04-03 22:38 UTC
